### ISSUE TITLE
"there was a problem to parsing this package" on Discord [Unknown Device]

### ISSUE THREAD

**Issue by JamesDAdams** [threethan/QuestAudioPatcher#2]
Hi,

i'm trying to patch discord with the version specified in the doc and i have the error :
`there was a problem to parsing this package`

Thanks

**Comment by threethan** [comment]
Thanks for creating an issue! This is unfortunately not enough information for me to figure out the problem.

Can you tell me what device you are running the patcher on & its firmware version?
Do other apps install successfully after being patched?

Additionally, it would be helpful if you're able to share the generated apk. You can do this by: 
1. Go to the APKs tab
2. Click and hold on "Discord" or "com.discord.app.App"
3. Select "Save to downloads"
4. Copy that file to your computer
5. Rename from .apk to .zip
6. Send here

**Comment by threethan** [comment]
Closing as stale & lacking information. If anyone encounters a similar problem, create a new issue with more information.
