### ISSUE TITLE
App closes upon opening another app [Quest 1]

### ISSUE THREAD

**Issue by alinanonymous** [threethan/QuestAudioPatcher#3]
I'll be frank. It seems to simply not work on my device. 
I'm using a Quest 1, don't know if it's an underpowered hardware issue or not.

When I open a game while in a call, the audio from Discord goes silent as soon as opening and participants can't hear my microphone, either. When I close the opened game, Discord is nowhere to be found, and I have to reopen it.

**Comment by threethan** [comment]
Seems like an issue unrelated to the patcher.

Does the app successfully install after patching?

Do you get audio while Discord is closed/minimized, but no other app is open in the foreground?

**Comment by alinanonymous** [comment]
Sorry for the late response.

Yes, it installs fine. It works pretty much perfectly while it's open. I can minimize it with the minimize button in the bottom left of the window. Off the top of my head, I cannot remember what closing it with X does. I can test later today.

**Comment by threethan** [comment]
Seems like this is a Quest 1 limitation, unrelated to the patcher. If there's something I could add to AndroidManifest.xml that would allow the app to stay open in the background on Quest 1, I can fix this. Otherwise, it's an unrelated limitation.
