### ISSUE TITLE
Discord unable to install patched verison

### ISSUE THREAD

**Issue by Fecfec97** [threethan/QuestAudioPatcher#5]
Hi there

When attempting to install the patched discord apk version 126 via your app it fails whilst displaying "Installing null..." when attempting to install.

Saving the patched app to Downloads then moving it to my PC to install via sidequest it continues to fail, but with this error:

`A task failed. Check the tasks screen for more info. com.discord_aee-signed.apk: /data/local/tmp/_stream.apk could not be installed [-124: Failed parse during installPackageLI: Targeting R+ (version 30 and above) requires the resources.arsc of installed APKs to be stored uncompressed and aligned on a 4-byte boundary]`

Currently attempting to see if: https://github.com/mathieures/convert-apk/ will help rectify the issue

**Comment by threethan** [comment]
~~Thanks for the error. Try this build, it uses a different version of zipalign that might be more reliable.
[QuestAudioPatcher_ZipAlignTest.zip](https://github.com/threethan/QuestAudioPatcher/files/13782296/QuestAudioPatcher_ZipAlignTest.zip)
(You will need to manually rename from *.zip to *.apk)~~

Try the newest release, I've changed the zipalign implementation to one that _should_ more reliably avoid this error.

By the way, which Quest device are you using?

**Comment by hackruu** [comment]
@threethan tried updated version you mentioned, discord installed successfully on quest3 on firmware 60, working fine! kudos!
