### ISSUE TITLE
request

### ISSUE THREAD

**Issue by ZAKsPop** [threethan/QuestAudioPatcher#6]
Would it be possible to make it so that This app could modify an APK that is not currently installed?  EX: I can put an  APK in a folder on the Quest then run this app and point it to that APK. Let it do its magic and spit out a modified APK that can then be installed... If this is already possible then I missed how to do it because I've not been able to.

**Comment by threethan** [comment]
I might do this if the patcher becomes more reliable. For now, installing the unmodified apk is an important troubleshooting step, as it confirms the app is installable in the first place; and therefore that any installation issues are a result of the patcher
