### ISSUE TITLE
Discord loose mic randomly

### ISSUE THREAD

**Issue by MiMillieuh** [threethan/QuestAudioPatcher#8]
Hello,

I've tried this app on my quest 3 and I can happily report that it works great.

However (And I don't know if it's related to the app or if it's patchable) I randomly loose the mic input when using discord for instance and I need to disconnect and reconnect from a channel to get it back.

Any solutions ? 

Thanks !

**Comment by threethan** [comment]
If it works at all, then it's not a problem with the patcher.

It's possible that Discord is being killed by the system for performance reasons, or that another application is requesting the mic instead.

**Comment by MiMillieuh** [comment]
I can still hear my friends so I guess it's more the mic issue, do you have any tricks to prevent the mic from being taken by another app?
